### PR TITLE
Shorten and simplify README.md

### PR DESCRIPTION
**Pull request by SmallJoker**
[Some notes](https://github.com/platomav/MCExtractor) [were mentioned multiple times within](https://github.com/platomav/MCExtractor) [the](https://github.com/platomav/MCExtractor) README file.
[The file format explanation](https://github.com/platomav/MCExtractor) [is now somewhat shorter](https://github.com/platomav/MCExtractor) [and less tiring to read](https://github.com/platomav/MCExtractor).

PS: This post is formatted exactly as intended.

### CODE REVIEW

**Comment by platomav** [comment]
It's better to have some text verbosity and even small repetition so that everyone can understand and not ask constantly what this and that means, what about my case with CPUID xxxxx etc. I know from personal experience from the Win-Raid forum. The "Platform ID" field is especially confusing for most people and cannot be tackled with a one liner. Either way, the README is small and people need to read it once so it cannot be that tiring. Thus, I don't believe any changes are needed for now.

**Comment by SmallJoker** [comment]
If you have suggestions to improve the field descriptions, please leave comments in the code. I'll adjust the readme accordingly afterwards.
The point of this PR is to make it easier to read, thus people will rather take the time to read it. Here's by the way the [GitHub-rendered version](https://github.com/SmallJoker/CPUMicrocodes/blob/4b3be05/README.md) in case you'd like to compare the visuals.

**Review by platomav — COMMENTED** [review]
It does look better at the GitHub-rendered version. I made some changes to make sure all info is still there, take a look if you like.

**Comment by SmallJoker** [comment]
:+1: Looks good. Thanks for taking care of the additions.

EDIT: I noticed the entries were not sorted by their appearance in the file name. It should be more intuitive to the user this way.

**Review by platomav — APPROVED** [review]
Perfect, thanks

**Pull request merged**
